# Generated by Django 6.1.1 on 2026-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('destination', models.CharField(max_length=150)),
                ('travel_date', models.DateField()),
                ('travellers', models.PositiveIntegerField()),
                ('vehicle', models.CharField(choices=[('Car', 'Car'), ('Tempo Traveller', 'Tempo Traveller'), ('Tourist Bus', 'Tourist Bus')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
